services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
